USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make
PACKAGE_VERSION=1.0
TITLE=OutsetMakefileExample
REVERSE_DOMAIN=com.github.erikng
PAYLOAD= \
		pack-usr-local-outset-login-custom-foo.py \
		pack-usr-local-outset-login-ebs-foo.sh \
		pack-usr-local-outset-login-fbpkg-foo.sh \
		pack-usr-local-outset-login-fbs-foo.sh \
		pack-usr-local-outset-login-levery-foo.sh \
		pack-usr-local-outset-login-lonce-foo.sh